### ISSUE TITLE
Sorting of Google songs fails due to no default in get call

### ISSUE THREAD

**Issue by fdw** [thebigmunch/google-music-scripts#16]
Thanks to your help, I started to sync my local collection with Google. To see what I needed to download, I called `gms sync down -vn $LOCAL_DIR`. Unfortunately, this crashes:
```
File "click/core.py", line 535, in invoke 
    return callback(*args, **kwargs)
File "google_music_scripts/commands/sync.py", line 154, in sync_down
    key=lambda song: (
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

If I read the code correctly, the problematic issue is here:
```
to_download.sort(
	key=lambda song: (
		song.get('artist'),
		song.get('album'),
		song.get('track_number')
	)
)
```
I definitely have some tracks that have neither album nor track_number, but all should have artist. Could it be that `gms` tries to compare the track_numbers even if it is not set?

**Comment by thebigmunch** [comment]
Hmmm. Something that has just coincidentally worked (or at least hasn't come up) since I first created ``gmusicapi-scripts`` 4 or more years ago. Yeah, there should definitely be defaults set in those get calls. Note that the same thing exists in the plain ``download`` command and the ``search`` command as well.

Thanks for the report. If you want a quick fix, you can change the lines in your installation from:

```
song.get('artist'),
song.get('album'),
song.get('track_number')
```

to:

```
song.get('artist', ''),
song.get('album', ''),
song.get('track_number', 0)
```

I should be pushing a new release soonish that will include this fix.

**Comment by thebigmunch** [comment]
To be fair, ``gmusicapi`` and, in turn, my ``gmusicapi-scripts`` started out Python 2-only. This only became a ``TypeError`` in Python 3. So, it's only been ~3 years that this could've come up : P

**Comment by fdw** [comment]
Awesome, thank you! :)
