### ISSUE TITLE
Uploaded files lose all idtag except "genre"

### ISSUE THREAD

**Issue by twiceth** [thebigmunch/google-music-scripts#28]
Sadly I'm not handy enough to be able to give you more informations.
I'm attatching a screenshot of what happens.
If you need anything else just ask,

btw, this happens when uploading from an Ubuntu 16.04 headless server.
google-music and gms are installed via pip.

![2019-01-29](https://user-images.githubusercontent.com/44921969/51939437-be75a080-240f-11e9-9473-ff2894229dcc.png)

**Comment by thebigmunch** [comment]
Either post a link here or send a link or file by email for me to check out.

**Comment by twiceth** [comment]
Keep in mind that it's not this single file. All the files that it tries to upload end up like that.
The library I'm uploading is on an ext4 filesystem, I don't know if that could be relevant.

[05. L'orto di Ovidio.zip](https://github.com/thebigmunch/google-music-scripts/files/2810042/05.L.orto.di.Ovidio.zip)

**Comment by thebigmunch** [comment]
> Keep in mind that it's not this single file. All the files that it tries to upload end up like that.

Well, no. It might be all the files you're trying. And, it's because that file (and probably the others) use ID3v2.2.

[This issue](https://github.com/thebigmunch/audio-metadata/issues/1) for my audio metadata library is the one to watch. ID3v2.3 and ID3v2.4 mostly share the necessary frame IDs, which makes the "easy" interface simple to share between them. ID3v2.2 has completely different frame IDs, and I haven't gotten to implementing the "easy" interface to ``audio-metadata`` for it yet.

So, you could choose to update the tags to a newer ID3 version on those files (many tag editors have an option to do that or will do that automatically on save) or wait until I implement that change in ``audio-metadata``.

Either way, closing this issue since it's an upstream issue.

**Comment by thebigmunch** [comment]
PS The reason genre was actually getting passed along is that it, for some reason, is using an ID3v2.3/4 frame ID for it when all the others are using ID3v2.2. That shouldn't actually be the case.

Anyway, I've banged out most of what should be needed in ``audio-metadata`` to properly support the easy interface for the 3 versions of ID3v2, so it shouldn't be too long before I release that.

**Comment by twiceth** [comment]
No need to rush. I'm looking on a way to convert all my files to those tags.

Thanks for your help

**Comment by thebigmunch** [comment]
Just an FYI, I've change ``audio-metadata`` to support separate field maps for different ID3v2 versions. So, things should work properly now.

**Comment by twiceth** [comment]
Yeah, I saw the update. 
That seems to have fixed that problem.
Thanks!
